/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleAgentsRouteImport } from './routes/_console/agents'
import { Route as ConsoleDeskRouteImport } from './routes/_console/desk'
import { Route as ConsoleGatesRouteImport } from './routes/_console/gates'
import { Route as ConsoleLeadsRouteImport } from './routes/_console/leads'
import { Route as ConsoleMessengerRouteImport } from './routes/_console/messenger'
import { Route as ConsolePlansRouteImport } from './routes/_console/plans'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'
import { Route as ConsoleTerminalRouteImport } from './routes/_console/terminal'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAgentsRoute = ConsoleAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDeskRoute = ConsoleDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleGatesRoute = ConsoleGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLeadsRoute = ConsoleLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMessengerRoute = ConsoleMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePlansRoute = ConsolePlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTerminalRoute = ConsoleTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/agents': typeof ConsoleAgentsRoute
  '/desk': typeof ConsoleDeskRoute
  '/gates': typeof ConsoleGatesRoute
  '/leads': typeof ConsoleLeadsRoute
  '/messenger': typeof ConsoleMessengerRoute
  '/plans': typeof ConsolePlansRoute
  '/settings': typeof ConsoleSettingsRoute
  '/terminal': typeof ConsoleTerminalRoute
}
export interface FileRoutesByTo {
  '/agents': typeof ConsoleAgentsRoute
  '/desk': typeof ConsoleDeskRoute
  '/gates': typeof ConsoleGatesRoute
  '/leads': typeof ConsoleLeadsRoute
  '/messenger': typeof ConsoleMessengerRoute
  '/plans': typeof ConsolePlansRoute
  '/settings': typeof ConsoleSettingsRoute
  '/terminal': typeof ConsoleTerminalRoute
  '/': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/agents': typeof ConsoleAgentsRoute
  '/_console/desk': typeof ConsoleDeskRoute
  '/_console/gates': typeof ConsoleGatesRoute
  '/_console/leads': typeof ConsoleLeadsRoute
  '/_console/messenger': typeof ConsoleMessengerRoute
  '/_console/plans': typeof ConsolePlansRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/terminal': typeof ConsoleTerminalRoute
  '/_console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/desk'
    | '/gates'
    | '/leads'
    | '/messenger'
    | '/plans'
    | '/settings'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/desk'
    | '/gates'
    | '/leads'
    | '/messenger'
    | '/plans'
    | '/settings'
    | '/terminal'
    | '/'
  id:
    | '__root__'
    | '/_console'
    | '/_console/agents'
    | '/_console/desk'
    | '/_console/gates'
    | '/_console/leads'
    | '/_console/messenger'
    | '/_console/plans'
    | '/_console/settings'
    | '/_console/terminal'
    | '/_console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/agents': {
      id: '/_console/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ConsoleAgentsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/desk': {
      id: '/_console/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof ConsoleDeskRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/gates': {
      id: '/_console/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof ConsoleGatesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/leads': {
      id: '/_console/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof ConsoleLeadsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/messenger': {
      id: '/_console/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof ConsoleMessengerRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/plans': {
      id: '/_console/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof ConsolePlansRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/terminal': {
      id: '/_console/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof ConsoleTerminalRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAgentsRoute: typeof ConsoleAgentsRoute
  ConsoleDeskRoute: typeof ConsoleDeskRoute
  ConsoleGatesRoute: typeof ConsoleGatesRoute
  ConsoleLeadsRoute: typeof ConsoleLeadsRoute
  ConsoleMessengerRoute: typeof ConsoleMessengerRoute
  ConsolePlansRoute: typeof ConsolePlansRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleTerminalRoute: typeof ConsoleTerminalRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAgentsRoute: ConsoleAgentsRoute,
  ConsoleDeskRoute: ConsoleDeskRoute,
  ConsoleGatesRoute: ConsoleGatesRoute,
  ConsoleLeadsRoute: ConsoleLeadsRoute,
  ConsoleMessengerRoute: ConsoleMessengerRoute,
  ConsolePlansRoute: ConsolePlansRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleTerminalRoute: ConsoleTerminalRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
